# Blog settings
permalink: /:title

# My variables
name: Yuri Freire Lima
description: software architect
google_verification: google3efd61b6b9deca0b.html

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge


# File management
include: [".htaccess"]
exclude:
  - bin
  - config.rb
  - Gemfile
  - Gemfile.lock
  - gems
  - Procfile
  - Rakefile
  - README.md
  - script
  - vendor
