# Blog settings
permalink: /blog/:title

# My variables
name: Yuri Freire Lima
description: Futuristic web design
google_verification: null

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge


# File management
include: [".htaccess"]
exclude:
  - bin
  - config.rb
  - Gemfile
  - Gemfile.lock
  - gems
  - Procfile
  - Rakefile
  - README.md
  - script
  - vendor
