# Permalinks
#
permalink: /:title

# Setup
title: Yuri's Blog
tagline: "Yuris blog"
description: 'My blog'
url: yurifrl.com
baseurl: ''
paginate: 5

# About/contact
author:
  name: Yuri Freire lima
  url:  https://twitter.com/yurifrl
  email: yurifrl@outlook.com

# Custom vars
version: 1.0.0

gems:
  - jekyll-paginate

exclude:
  - bin
  - config.rb
  - Gemfile
  - Gemfile.lock
  - gems
  - Procfile
  - Rakefile
  - README.md
  - script
  - vendor
  - docker-compose.yml
