# Blog settings
permalink: /:title

# My variables, this will go to `site` variable
title: Yuri F. Lima
description: Platform Engineer
google_verification: google3efd61b6b9deca0b.html
collections_dir: collections
collections:
  cheat_sheets:
    output: true

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# File management
include: [".htaccess"]
exclude:
  - README.md
  - LICENSE
  - docker-compose.yml

post_layout: post
page_layout: default
