# Blog settings
permalink: /:title

# My variables, this will go to `site` variable
name: Yuri Freire Lima
description: software architect
google_verification: google3efd61b6b9deca0b.html

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# File management
include: [".htaccess"]
exclude:
  - README.md
  - TODO.md
  - work.log
  - LICENSE
  - docker-compose.yml

post_layout: post
page_layout: default
